export const technologies = [
      { name: 'CSS', icon: 'images/tech/css.png' },
      { name: 'JS', icon: 'images/tech/javascript.png' },
      { name: 'react', icon: 'images/tech/java.png' },
      { name: 'angular', icon: 'images/tech/angular.png' },
      { name: 'springboot', icon: 'images/tech/spring-boot.png' },
      { name: 'tailwind', icon: 'images/tech/tailwind.png' },
      { name: 'nodejs', icon: 'images/tech/nodejs.png' },
      { name: 'React JS', icon: 'images/tech/reactjs.png' },
      { name: 'MongoDB', icon: 'images/tech/mongodb.png' },
      { name: 'Mysql', icon: 'images/tech/mysql.png' },
      { name: 'SqlServer', icon: 'images/tech/sql-server.png' },
      { name: 'scss', icon: 'images/tech/scss.png' },
      { name: 'figma', icon: 'images/tech/figma.png' },
      { name: 'docker', icon: 'images/tech/docker.png' },
      { name: 'threejs', icon: 'images/tech/threejs.svg' },
];
const postionsRows = {
      normal: {
            sartRow: 4,
      },
      m1280: {
            sartRow: 8,
      },
      m810: {
            sartRow: 16,
      },
      m480: {
            sartRow: 27,
      },
};
export const layouts = {
      normal: {
            positions: [
                  [-28, postionsRows.normal.sartRow, 0],
                  [-20, postionsRows.normal.sartRow, 0],
                  [-12, postionsRows.normal.sartRow, 0],
                  [-4, postionsRows.normal.sartRow, 0],
                  [4, postionsRows.normal.sartRow, 0],
                  [12, postionsRows.normal.sartRow, 0],
                  [20, postionsRows.normal.sartRow, 0],
                  [28, postionsRows.normal.sartRow, 0],
                  [-24, postionsRows.normal.sartRow - 8, 0],
                  [-16, postionsRows.normal.sartRow - 8, 0],
                  [-8, postionsRows.normal.sartRow - 8, 0],
                  [0, postionsRows.normal.sartRow - 8, 0],
                  [8, postionsRows.normal.sartRow - 8, 0],
                  [16, postionsRows.normal.sartRow - 8, 0],
                  [24, postionsRows.normal.sartRow - 8, 0],
            ],
            canvasHeight: '350px',
            zoom: 20,
      },
      m1280: {
            positions: [
                  [-16, postionsRows.m1280.sartRow, 0],
                  [-8, postionsRows.m1280.sartRow, 0],
                  [0, postionsRows.m1280.sartRow, 0],
                  [8, postionsRows.m1280.sartRow, 0],
                  [16, postionsRows.m1280.sartRow, 0],
                  [-16, postionsRows.m1280.sartRow - 8, 0],
                  [-8, postionsRows.m1280.sartRow - 8, 0],
                  [0, postionsRows.m1280.sartRow - 8, 0],
                  [8, postionsRows.m1280.sartRow - 8, 0],
                  [16, postionsRows.m1280.sartRow - 8, 0],
                  [-16, postionsRows.m1280.sartRow - 16, 0],
                  [-8, postionsRows.m1280.sartRow - 16, 0],
                  [0, postionsRows.m1280.sartRow - 16, 0],
                  [8, postionsRows.m1280.sartRow - 16, 0],
                  [16, postionsRows.m1280.sartRow - 16, 0],
            ],
            canvasHeight: '550px',
            zoom: 18,
      },
      m810: {
            positions: [
                  [-8, postionsRows.m810.sartRow, 0],
                  [0, postionsRows.m810.sartRow, 0],
                  [8, postionsRows.m810.sartRow, 0],
                  [-8, postionsRows.m810.sartRow - 8, 0],
                  [0, postionsRows.m810.sartRow - 8, 0],
                  [8, postionsRows.m810.sartRow - 8, 0],
                  [-8, postionsRows.m810.sartRow - 16, 0],
                  [0, postionsRows.m810.sartRow - 16, 0],
                  [8, postionsRows.m810.sartRow - 16, 0],
                  [-8, postionsRows.m810.sartRow - 24, 0],
                  [0, postionsRows.m810.sartRow - 24, 0],
                  [8, postionsRows.m810.sartRow - 24, 0],
                  [-8, postionsRows.m810.sartRow - 32, 0],
                  [0, postionsRows.m810.sartRow - 32, 0],
                  [8, postionsRows.m810.sartRow - 32, 0],
            ],
            canvasHeight: '950px',
            zoom: 15,
      },
      m480: {
            positions: [
                  [-4, postionsRows.m480.sartRow, 0],
                  [4, postionsRows.m480.sartRow, 0],
                  [-4, postionsRows.m480.sartRow - 8, 0],
                  [4, postionsRows.m480.sartRow - 8, 0],
                  [-4, postionsRows.m480.sartRow - 16, 0],
                  [4, postionsRows.m480.sartRow - 16, 0],
                  [-4, postionsRows.m480.sartRow - 24, 0],
                  [4, postionsRows.m480.sartRow - 24, 0],
                  [-4, postionsRows.m480.sartRow - 32, 0],
                  [4, postionsRows.m480.sartRow - 32, 0],
                  [-4, postionsRows.m480.sartRow - 40, 0],
                  [4, postionsRows.m480.sartRow - 40, 0],
                  [-4, postionsRows.m480.sartRow - 48, 0],
                  [4, postionsRows.m480.sartRow - 48, 0],
                  [0, postionsRows.m480.sartRow - 56, 0],
            ],
            canvasHeight: '1182px',
            zoom: 12,
      },
};
