export const technologies = [
    { name: "CSS", icon: "images/tech/css.png" },
    { name: "JS", icon: "images/tech/javascript.png" },
    { name: "react", icon: "images/tech/java.png" },
    { name: "angular", icon: "images/tech/angular.png" },
    { name: "springboot", icon: "images/tech/spring-boot.png" },
    { name: "tailwind", icon: "images/tech/tailwind.png" },
    { name: "nodejs", icon: "images/tech/nodejs.png" },
    { name: "React JS", icon: "images/tech/reactjs.png" },
    { name: "MongoDB", icon: "images/tech/mongodb.png" },
    { name: "Mysql", icon: "images/tech/mysql.png" },
    { name: "SqlServer", icon: "images/tech/sql-server.png" },
    { name: "scss", icon: "images/tech/scss.png" },
    { name: "figma", icon: "images/tech/figma.png" },
    { name: "docker", icon: "images/tech/docker.png" },
    { name: "threejs", icon: "images/tech/threejs.svg" },
];
export const layouts = {
    normal: {
        positions: [
            [-28, 4.5, 0],
            [-20, 4.5, 0],
            [-12, 4.5, 0],
            [-4, 4.5, 0],
            [4, 4.5, 0],
            [12, 4.5, 0],
            [20, 4.5, 0],
            [28, 4.5, 0],
            [-24, -3, 0],
            [-16, -3, 0],
            [-8, -3, 0],
            [0, -3, 0],
            [8, -3, 0],
            [16, -3, 0],
            [24, -3, 0],
        ],
        canvasHeight: "350px",
        zoom: 20,
    },
    m1280: {
        positions: [
            [-16, 8, 0],
            [-8, 8, 0],
            [0, 8, 0],
            [8, 8, 0],
            [16, 8, 0],
            [-16, 0, 0],
            [-8, 0, 0],
            [0, 0, 0],
            [8, 0, 0],
            [16, 0, 0],
            [-16, -8, 0],
            [-8, -8, 0],
            [0, -8, 0],
            [8, -8, 0],
            [16, -8, 0],
        ],
        canvasHeight: "550px",
        zoom: 18,
    },
    m810: {
        positions: [
            [-8, 16, 0],
            [0, 16, 0],
            [8, 16, 0],
            [-8, 8, 0],
            [0, 8, 0],
            [8, 8, 0],
            [-8, 0, 0],
            [0, 0, 0],
            [8, 0, 0],
            [-8, -8, 0],
            [0, -8, 0],
            [8, -8, 0],
            [-8, -16, 0],
            [0, -16, 0],
            [8, -16, 0],
        ],
        canvasHeight: "950px",
        zoom: 15,
    },
    m480: {
        positions: [
            [-4, 24, 0],
            [4, 24, 0],
            [-4, 16, 0],
            [4, 16, 0],
            [-4, 8, 0],
            [4, 8, 0],
            [-4, 0, 0],
            [4, 0, 0],
            [-4, -8, 0],
            [4, -8, 0],
            [-4, -16, 0],
            [4, -16, 0],
            [-4, -24, 0],
            [4, -24, 0],
            [0, -32, 0],
        ],
        canvasHeight: "1200px",
        zoom: 12,
    },
};